service: process-logs

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.ts
    packager: yarn
    includeModules: true # Enable auto-packing of external modules

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  memorySize: 128
  timeout: 300
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'}
    STAGE: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "${self:custom.secretsArnPrefix}/splunk/httpCollector/awsLogs/token-*"
      Resource: "*"
    - Effect: Allow
      Action:
        - cloudwatch:*
        - logs:*
        - events:*
      Resource: "*"

functions:
  processLogs:
    handler: src/processLogs.processLogs

